### ISSUE TITLE
Failed to resolve: android-spatialite

### ISSUE THREAD

**Issue by mdumrauf** [sevar83/android-spatialite#8]
I am getting this error while trying to download dependencies. I looked for the package in Maven central and Jcenter and it does not exist. Was it removed?

**Comment by sevar83** [comment]
Hi, did you add the JitPack repository like in the README? This library is not available on Maven Central, only through JitPack. You can check the build status: https://jitpack.io/#sevar83/android-spatialite

**Comment by mdumrauf** [comment]
I do actually.
```
repositories {
    maven {
        url 'https://maven.google.com'
    }
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    flatDir {
        dirs 'libs'
    }
}
```

**Comment by mdumrauf** [comment]
I found the error. I was using 2.0.0-RC0 (for a long time now) and I see it has a build error on Jitpack. I guess a new build was triggered, failed and made it unusable.

Does 2.0.0 have latest changes on 2.0.0-RC0?

**Comment by sevar83** [comment]
2.0.0 is latest as far as I recall.

**Comment by invweb** [comment]
doesn't seem to work anymore
Having: Failed to resolve: com.github.sevar83:android-spatialite:2.0.1
